# Generated by Django 4.2.8 on 2025-07-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_path', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='translations.translationnamespace')),
            ],
            options={
                'unique_together': {('namespace', 'key_path')},
            },
        ),
        migrations.CreateModel(
            name='TranslationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('ar', 'Arabic'), ('kz', 'Kazakh')], max_length=10)),
                ('text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='translations.translationkey')),
            ],
            options={
                'unique_together': {('key', 'language')},
            },
        ),
    ]
